Carts/urls.py
from django.urls import path
from . import views

app_name = 'Carts'
urlpatterns = [
    path('',views.cart,name='cart'),
    path('cart-update/',views.update_cart,name='cart-update'),
    path('display-cart/',views.display_cart,name='display-cart'),
    path('clear-cart/',views.clear_cart,name='clear-cart'),
    path('stripe-page/',views.stripe_page,name='stripe-page'),
    path('config/', views.stripe_config,name='config'),
    path('create-checkout-session/', views.create_checkout_session,name='checkout_session'),
]

Search/urls.py
from django.urls import path
from . import views

app_name = 'Search'
urlpatterns = [
    path('',views.search,name='search'),
]

acubook/urls.py
from django.urls import path
from . import views

app_name = 'acubook'
urlpatterns = [
    path('',views.index,name='index'),
    path('bookstore/arts',views.arts,name='arts'),
    path('bookstore/business',views.business,name='business'),
    path('bookstore/christianbooks',views.christian,name='christian'),
    path('bookstore/motivational',views.motivational,name='motivational'),
    path('bookstore/nigerian',views.nigerian,name='nigerian'),
    path('bookstore/science',views.science,name='science'),
    path('bookstore/teenbooks',views.teenbooks,name='teenbooks'),
    path('bookstore/about_us',views.about_us,name='about_us'),
    path('bookstore/register',views.register,name='register'),
    path('bookstore/logout',views.user_logout,name='logout'),
    path('bookstore/user_login',views.user_login,name='user_login'),
    path('bookstore/description',views.description,name='description'),
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('acubook.urls')),
    path('cart/',include('Carts.urls')),
    path('search/',include('Search.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

acubook/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.
class UserProfileInfo(models.Model):

	user = models.OneToOneField(User,on_delete=models.CASCADE)

	#additional fields
	def __str__(self):
		return str(self.user)

def create_user_profile(sender,instance,created,**kwargs):
	if created:
		UserProfileInfo.objects.create(user=instance)
post_save.connect(create_user_profile,sender=User) 

	

class Category(models.Model):
	categories = [
		('Arts and Literature','Arts and Literature'),
		('Science','Science'),
		('Christian Books','Christian Books'),
		('Nigerian and African Authors','Nigerian and African Authors'),
		('Motivational','Motivational'),
		('Business','Business'),
		('Teen Books','Teen Books')
	]
	categorys = models.CharField(max_length=256,choices=categories,default='Arts and Literature')

	def __str__(self):
		return str(self.categorys)

class BookInfo(models.Model):
	Book_image = models.ImageField(null=True,blank=True)
	Title = models.CharField(max_length=265,unique=True)
	Authors = models.CharField(max_length=256)
	Publish_year = models.IntegerField()
	Price = models.IntegerField()
	Description = models.TextField()
	Quantity = models.IntegerField(default=1)
	bookcategories = models.ManyToManyField(Category)


	def __str__(self):
		return self.Title

acubook/forms.py
from django import forms
from django.contrib.auth.models import User
from acubook.models import UserProfileInfo,BookInfo
from django.core import validators

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
	confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

	class Meta():
		model = User
		fields = ('username','email','password')

		widgets = {
			'username' : forms.TextInput(attrs={'class':'form-control'}),
			'email' : forms.EmailInput(attrs={'class':'form-control','required':'required',
												'placeholder':'a@gmail.com'}),
		}
		help_texts = {
			'username':None
		}

	def clean(self):
		cleaned_data = super().clean()
		password = cleaned_data.get("password")
		confirm_password = cleaned_data.get("confirm_password")

		if password != confirm_password:
			raise forms.ValidationError('password and confirm_password do not match')

acubook/views.py
from django.shortcuts import render,redirect
from .forms import UserForm
from django.contrib import messages
from django.http import Http404

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
from acubook.models import Category,BookInfo,UserProfileInfo
from Carts.models import Cart,CartItem

# Create your views here.
def index(request):
	artsbook = BookInfo.objects.filter(bookcategories__categorys="Arts and Literature")
	sciencebook = BookInfo.objects.filter(bookcategories__categorys="Science")
	christianbook = BookInfo.objects.filter(bookcategories__categorys="Christian Books")
	nigerianbook = BookInfo.objects.filter(bookcategories__categorys="Nigerian and African Authors")
	businessbook = BookInfo.objects.filter(bookcategories__categorys="Business")
	teenbook = BookInfo.objects.filter(bookcategories__categorys="Teen Books")
	motivatebook = BookInfo.objects.filter(bookcategories__categorys="Motivational")

	username = None
	if request.user.is_authenticated:
		username = request.user

		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)

		cart_items = CartItem.objects.filter(cart=carts)

		total_itemNum =  CartItem.objects.filter(cart=carts).count()
	else:
		total_itemNum = 0

	context = {"artsbook":artsbook,"sciencebook":sciencebook,"christianbook":christianbook,
				"nigerianbook":nigerianbook,"businessbook":businessbook,"teenbook":teenbook,
				"motivatebook":motivatebook,'total_cartitem':total_itemNum}
	return render(request,'acubook/index.html',context)

#FOR cart and order page.Login required will be used.

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('acubook:index'))

def arts(request):
	artsbook = BookInfo.objects.filter(bookcategories__categorys="Arts and Literature")

	username = None
	if request.user.is_authenticated:
		username = request.user

		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)

		cart_items = CartItem.objects.filter(cart=carts)

		total_itemNum =  CartItem.objects.filter(cart=carts).count()
	else:
		total_itemNum = 0

	context = {"artsbook":artsbook,'total_cartitem':total_itemNum}
	return render(request,'acubook/arts.html',context)

def business(request):
	businessbook = BookInfo.objects.filter(bookcategories__categorys="Business")

	username = None
	if request.user.is_authenticated:
		username = request.user

		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)
		cart_items = CartItem.objects.filter(cart=carts)

		total_itemNum =  CartItem.objects.filter(cart=carts).count()
	else:
		total_itemNum = 0

	context = {"businessbook":businessbook,'total_cartitem':total_itemNum}
	return render(request,'acubook/business.html',context)

def christian(request):
	christianbook = BookInfo.objects.filter(bookcategories__categorys="Christian Books")

	username = None
	if request.user.is_authenticated:
		username = request.user

		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)

		cart_items = CartItem.objects.filter(cart=carts)

		total_itemNum =  CartItem.objects.filter(cart=carts).count()
	else:
		total_itemNum = 0

	context = {"christianbook":christianbook,'total_cartitem':total_itemNum}
	return render(request,'acubook/christianbooks.html',context)

def motivational(request):
	motivatebook = BookInfo.objects.filter(bookcategories__categorys="Motivational")

	username = None
	if request.user.is_authenticated:
		username = request.user

		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)
		cart_items = CartItem.objects.filter(cart=carts)

		total_itemNum =  CartItem.objects.filter(cart=carts).count()
	else:
		total_itemNum = 0

	context = {"motivatebook" : motivatebook,'total_cartitem':total_itemNum}
	return render(request,'acubook/motivational.html',context)

def nigerian(request):
	nigerianbook = BookInfo.objects.filter(bookcategories__categorys="Nigerian and African Authors")

	username = None
	if request.user.is_authenticated:
		username = request.user

		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)
		cart_items = CartItem.objects.filter(cart=carts)

		total_itemNum =  CartItem.objects.filter(cart=carts).count()
	else:
		total_itemNum = 0

	context = {"nigerianbook":nigerianbook,'total_cartitem':total_itemNum}
	return render(request,'acubook/nigerian.html',context)

def science(request):
	sciencebook = BookInfo.objects.filter(bookcategories__categorys="Science")

	username = None
	if request.user.is_authenticated:
		username = request.user

		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)
		cart_items = CartItem.objects.filter(cart=carts)

		total_itemNum =  CartItem.objects.filter(cart=carts).count()
	else:
		total_itemNum = 0

	context = {"sciencebook":sciencebook,'total_cartitem':total_itemNum}
	return render(request,'acubook/science.html',context)

def teenbooks(request):
	teenbook = BookInfo.objects.filter(bookcategories__categorys="Teen Books")

	username = None
	if request.user.is_authenticated:
		username = request.user

		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)

		cart_items = CartItem.objects.filter(cart=carts)

		total_itemNum =  CartItem.objects.filter(cart=carts).count()
	else:
		total_itemNum = 0

	context = {"teenbook":teenbook,'total_cartitem':total_itemNum}
	return render(request,'acubook/teenbooks.html',context)

def about_us(request):
	username = None
	if request.user.is_authenticated:
		username = request.user
		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)

		cart_items = CartItem.objects.filter(cart=carts)

		total_itemNum =  CartItem.objects.filter(cart=carts).count()
	else:
		total_itemNum = 0
	return render(request,'acubook/aboutus.html',context={'total_cartitem':total_itemNum})

def description(request):
	t_query = request.GET.get("title")
	c_query = request.GET.get("category")
	
	if c_query == 'Arts and Literature':
		arts = BookInfo.objects.filter(Title = t_query)

		username = None
		if request.user.is_authenticated:
			username = request.user
			user_profile = UserProfileInfo.objects.get(user=username)
			Cart.objects.get_or_create(currentuser=user_profile)
			carts = Cart.objects.get(currentuser=user_profile)

			cart_items = CartItem.objects.filter(cart=carts)

			total_itemNum =  CartItem.objects.filter(cart=carts).count()
		else:
			total_itemNum = 0

		context = {"arts":arts,'total_cartitem':total_itemNum}
		return render(request,'acubook/bookdescription.html',context)
		
	elif c_query == 'Science':
		sciences = BookInfo.objects.filter(Title = t_query)

		username = None
		if request.user.is_authenticated:
			username = request.user
			user_profile = UserProfileInfo.objects.get(user=username)
			Cart.objects.get_or_create(currentuser=user_profile)
			carts = Cart.objects.get(currentuser=user_profile)

			cart_items = CartItem.objects.filter(cart=carts)

			total_itemNum =  CartItem.objects.filter(cart=carts).count()
		else:
			total_itemNum = 0
		context = {"sciences":sciences,'total_cartitem':total_itemNum}
		return render(request,'acubook/bookdescription.html',context)

	elif c_query == 'Business':
		business = BookInfo.objects.filter(Title = t_query)

		username = None
		if request.user.is_authenticated:
			username = request.user
			user_profile = UserProfileInfo.objects.get(user=username)
			Cart.objects.get_or_create(currentuser=user_profile)
			carts = Cart.objects.get(currentuser=user_profile)

			cart_items = CartItem.objects.filter(cart=carts)

			total_itemNum =  CartItem.objects.filter(cart=carts).count()
		else:
			total_itemNum = 0
		context = {"business":business,'total_cartitem':total_itemNum}
		return render(request,'acubook/bookdescription.html',context)

	elif c_query == 'Christian Books':
		christianbks = BookInfo.objects.filter(Title = t_query)
		username = None
		if request.user.is_authenticated:
			username = request.user
			user_profile = UserProfileInfo.objects.get(user=username)
			Cart.objects.get_or_create(currentuser=user_profile)
			carts = Cart.objects.get(currentuser=user_profile)

			cart_items = CartItem.objects.filter(cart=carts)

			total_itemNum =  CartItem.objects.filter(cart=carts).count()
		else:
			total_itemNum = 0
		context = {"christianbks":christianbks,'total_cartitem':total_itemNum}
		return render(request,'acubook/bookdescription.html',context)

	elif c_query == 'Motivational':
		motivational = BookInfo.objects.filter(Title = t_query)
		username = None
		if request.user.is_authenticated:
			username = request.user
			user_profile = UserProfileInfo.objects.get(user=username)
			Cart.objects.get_or_create(currentuser=user_profile)
			carts = Cart.objects.get(currentuser=user_profile)
			cart_items = CartItem.objects.filter(cart=carts)

			total_itemNum =  CartItem.objects.filter(cart=carts).count()
		else:
			total_itemNum = 0
		context = {"motivational":motivational,'total_cartitem':total_itemNum}

templates/acubook/arts.html
{% extends "acubook/base.html" %}
{% block body_block %}
{% load static %}

    <!-- First Book section Arts and Literature -->
    <div class="container padding ">
      <div class="row padding my-6">
        <div class="col-12 text-center ">
          <h2 class="cardheader">Arts and Literature</h2>   <!--Font Awesome has to be used in the headers-->
        </div>
        </div>
      {% if artsbook %}
        <div class="row padding my-6">
      {% for arts in artsbook %}
        <div class="col-md-6 col-lg-3 col-xs-6 col-sm-6 post">
          <div class="card"> 
            <a href="{% url 'acubook:description' %}?title={{ arts.Title }}&category=Arts and Literature"><img src="{{ arts.Book_image.url }}" alt="Images"class="card-img-top"style="height:250px;"></a>
            <div class="card-body">
              <h4 class="card-title">{{ arts.Title }}</h4>
              <p class="card-text">#{{ arts.Price }}</p>
              <form  action="{% url 'Carts:cart' %}?title={{ arts.Title }}" method="POST">
                {% csrf_token %}
                <p>
                <input type="hidden" name="quantity" value="1"></p>
                <button class="btn btn-dark carts">Add to Cart</button>
              </form>

            </div>
          </div>
        </div>
      {% endfor %}
      </div>
      {% endif %}
    </div>
{% endblock %}

templates/acubook/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ACU BOOKSTORE</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/mystyle.css'%}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://js.stripe.com/v3/"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">



  </head>
  <body>
    <header>
      <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg navbar-light bg-light headers">
          <ul class="navbar-nav ml-auto mr-auto mt-2 mt-lg-0 ">
            <li  class="nav-item"><a href="#" class="nav-link ajayi">Ajayi Crowther University</a></li>
          </ul>
          <ul class="navbar-nav ">
            <li class="nav-item"><a href="{% url 'acubook:register'%}" class="acureg nav-link ">Register</a></li>

            {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'acubook:logout' %}" class="acureg nav-link ">Logout</a></li>

            {% else %}
             <li class="nav-item"><a href="{% url 'acubook:user_login' %}" class="acureg nav-link ">Login</a></li>

            {% endif %}

          </ul>
        </nav>
      </div>

  </header>

  <!-- Navigation panel -->
    <div class="container-fluid p-0 text-center acunav sticky-top">
        <nav class="navbar navbar-expand-lg navbar-light bg-light acuhead">
        <a class="navbar-brand" href="{% url 'acubook:index' %}"><img src="{% static 'images/acu.jpeg' %}" id="acuimg"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav ml-auto mr-auto mt-2 mt-lg-0">
            <li class="nav-item active ">
              <a class="nav-link middle" href="{% url 'acubook:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown ">
              <a class="nav-link dropdown-toggle middle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'acubook:arts' %}">Arts and Literature</a>
                <br>
                <a class="dropdown-item" href="{% url 'acubook:science' %}">Science</a>
                <br>
                <a class="dropdown-item" href="{% url 'acubook:christian' %}">Christian Books</a>
                <br>
                <a class="dropdown-item" href="{% url 'acubook:nigerian' %}">Nigerian and African Authors</a>
                <br>
                <a class="dropdown-item" href="{% url 'acubook:motivational' %}">Motivational</a>
                <br>
                <a class="dropdown-item" href="{% url 'acubook:business' %}">Business</a>
                <br>
                <a class="dropdown-item" href="{% url 'acubook:teenbooks' %}">Teen Books</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link middle" href="#footer">Contacts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link middle" href="{% url 'acubook:about_us' %}">About Us</a>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link right" href="{% url 'Carts:display-cart' %}">Cart&nbsp<span class="badge badge-info">{{ total_cartitem }}</span></a>
            </li>
            <form class="form-inline" action="{% url 'Search:search' %}" post="GET">
              <input class="form-control mr-sm-2" name="title" type="search" placeholder="Search Book Title" aria-label="Search">
              <button class="btn btn-outline-dark my-2 my-sm-0 navbutton" type="submit">Search</button>
            </form>
          </ul>
        </div>
      </nav>
    </div>

    {% block body_block %}
    {% endblock %}


  <!-- Footer -->
    <div class="container-fluid padding">
        <div class="row text-center footer" id="footer">
            <div class="col-md-6">
                <h2>Address</h2>
                <hr class="light">
                <p>555-555-5555</p>
                <p>email@myemail.com</p>
                <p>100 Street Name</p>
                <p>Oyo Town, Oyo State</p>
            </div>

            <div class="col-md-6">
                <hr class="light">
                <p>Our Hours</p>
                <hr class="light">
                <p>Monday - Friday : 9am - 4pm</p>
                <p>Saturday: Closed</p>
                <p>Sunday: Closed</p>
            </div>

            <div class="col-12">
                <hr class="light-100">
                <h5>&copy: acu.edu.ng</h5>
            </div>
        </div>
    </div>

  <script >
    $(document).ready(function(){

      $('.col-lg-3').hover(

      // trigger when on hover
        function(){
          $(this).animate({
            marginTop: "-=1%",
          },200);

        },

      // trigger when hover out
        function(){
          $(this).animate({
            marginTop: "0%"
          },200);
        }

      );

    });
  </script>
</body>
</html>

templates/acubook/business.html
<!DOCTYPE html>
{% extends "acubook/base.html" %}
{% block body_block %}
{% load static %}

    <!-- First Book section Business -->
    <div class="container padding ">
      <div class="row padding my-6">
        <div class="col-12 text-center ">
          <h2 class="cardheader">Business</h2>   <!--Font Awesome has to be used in the headers-->
        </div>
      </div>

      {% if businessbook %}  
        <div class="row padding my-6">
        {% for business in businessbook %}
        <div class="col-md-6 col-lg-3 col-xs-6 col-sm-6 post">
          <div class="card">
  					<a href="{% url 'acubook:description' %}?title={{ business.Title }}&category=Business"><img src="{{ business.Book_image.url }}" alt="Images"class="card-img-top"style="height:250px;"></a>
  					<div class="card-body">
  						<h4 class="card-title">{{ business.Title }}</h4>
              <p class="card-text">#{{ business.Price }}</p>
  						<form  action="{% url 'Carts:cart' %}?title={{ business.Title }}" method="POST">
                {% csrf_token %}
                <p>
                <input type="hidden" name="quantity" value="1"></p>
                <button class="btn btn-dark carts">Add to Cart</button>
              </form>

  					</div>
          </div>
          </div>
          {% endfor %}
        </div>
        {% endif %}
    </div>

  {% endblock %}

templates/acubook/christianbooks.html
<!DOCTYPE html>
{% extends "acubook/base.html" %}
{% block body_block %}
{% load static %}
    <!-- First Book section Science -->
    <div class="container padding ">
      <div class="row padding my-6">
        <div class="col-12 text-center ">
          <h2 class="cardheader">Christian Books</h2>   <!--Font Awesome has to be used in the headers-->
        </div>
      </div>

      {% if christianbook %}
        <div class="row padding my-6">
        {% for christian in christianbook %}
        <div class="col-md-6 col-lg-3 col-xs-6 col-sm-6 post">
          <div class="card">
  					<a href="{% url 'acubook:description' %}?title={{ christian.Title }}&category=Christian Books"><img src="{{ christian.Book_image.url }}" alt="Images"class="card-img-top"style="height:250px;"></a>
  					<div class="card-body">
  						<h4 class="card-title">{{ christian.Title }}</h4>
              <p class="card-text">#{{ christian.Price }}</p>
  						<form  action="{% url 'Carts:cart' %}?title={{ christian.Title }}" method="POST">
                {% csrf_token %}
                <p>
                <input type="hidden" name="quantity" value="1"></p>
                <button class="btn btn-dark carts">Add to Cart</button>
              </form>

  					</div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>

{% endblock %}

templates/acubook/motivational.html
<!DOCTYPE html>
{% extends "acubook/base.html" %}
{% block body_block %}
{% load static %}
    <!-- First Book section Motivational -->
    <div class="container padding ">
      <div class="row padding my-6">
        <div class="col-12 text-center ">
          <h2 class="cardheader">Motivational</h2>   <!--Font Awesome has to be used in the headers-->
        </div>
      </div>
      {% if motivatebook %}
        <div class="row padding my-6">
          {% for motivate in motivatebook %}
        <div class="col-md-6 col-lg-3 col-xs-6 col-sm-6 post">
          <div class="card">
  					<a href="{% url 'acubook:description' %}?title={{ motivate.Title }}&category=Motivational"><img src="{{ motivate.Book_image.url }}" alt="Images"class="card-img-top"style="height:250px;"></a>
  					<div class="card-body">
  						<h4 class="card-title">{{ motivate.Title }}</h4>
              <p class="card-text">#{{ motivate.Price }}</p>
  						<form  action="{% url 'Carts:cart' %}?title={{ motivate.Title }}" method="POST">
                {% csrf_token %}
                <p>
                <input type="hidden" name="quantity" value="1"></p>
                <button class="btn btn-dark carts">Add to Cart</button>
              </form>

  					</div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
      </div>

{% endblock %}

templates/acubook/nigerian.html
<!DOCTYPE html>
{% extends "acubook/base.html" %}
{% block body_block %}
{% load static %}
    <!-- First Book section Nigerian and African Authors -->
    <div class="container padding ">
      <div class="row padding my-6">
        <div class="col-12 text-center ">
          <h2 class="cardheader">Nigerian and African Authors</h2>   <!--Font Awesome has to be used in the headers-->
        </div>
      </div>
      {% if nigerianbook %}
        <div class="row padding my-6">
      {% for nigerian in nigerianbook %}
        <div class="col-md-6 col-lg-3 col-xs-6 col-sm-6 post">
          <div class="card">
  					<a href="{% url 'acubook:description' %}?title={{ nigerian.Title }}&category=Nigerian Books"><img src="{{ nigerian.Book_image.url }}" alt="Images"class="card-img-top"style="height:250px;"></a>
  					<div class="card-body">
  						<h4 class="card-title">{{ nigerian.Title }}</h4>
              <p class="card-text">#{{ nigerian.Price }}</p>
  						<form  action="{% url 'Carts:cart' %}?title={{ nigerian.Title }}" method="POST">
                {% csrf_token %}
                <p>
                <input type="hidden" name="quantity" value="1"></p>
                <button class="btn btn-dark carts">Add to Cart</button>
              </form>

  					</div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  {% endblock %}