Carts/urls.py
from django.urls import path
from . import views

app_name = 'Carts'
urlpatterns = [
    path('',views.cart,name='cart'),
    path('cart-update/',views.update_cart,name='cart-update'),
    path('display-cart/',views.display_cart,name='display-cart'),
    path('clear-cart/',views.clear_cart,name='clear-cart'),
    path('stripe-page/',views.stripe_page,name='stripe-page'),
    path('config/', views.stripe_config,name='config'),
    path('create-checkout-session/', views.create_checkout_session,name='checkout_session'),
]

acubook/urls.py
from django.urls import path
from . import views

app_name = 'acubook'
urlpatterns = [
    path('',views.index,name='index'),
    path('bookstore/arts',views.arts,name='arts'),
    path('bookstore/business',views.business,name='business'),
    path('bookstore/christianbooks',views.christian,name='christian'),
    path('bookstore/motivational',views.motivational,name='motivational'),
    path('bookstore/nigerian',views.nigerian,name='nigerian'),
    path('bookstore/science',views.science,name='science'),
    path('bookstore/teenbooks',views.teenbooks,name='teenbooks'),
    path('bookstore/about_us',views.about_us,name='about_us'),
    path('bookstore/register',views.register,name='register'),
    path('bookstore/logout',views.user_logout,name='logout'),
    path('bookstore/user_login',views.user_login,name='user_login'),
    path('bookstore/description',views.description,name='description'),
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('acubook.urls')),
    path('cart/',include('Carts.urls')),
    path('search/',include('Search.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Carts/models.py
from django.db import models
from django.contrib.auth.models import User
from acubook.models import BookInfo,UserProfileInfo
# Create your models here.

class Cart(models.Model):
	currentuser = models.OneToOneField(UserProfileInfo,on_delete=models.CASCADE)
	timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
	updated = models.DateTimeField(auto_now_add=False,auto_now=True)

	def __str__(self):
		return "Cart name: %s" %(self.currentuser)

class CartItem(models.Model):
	cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
	book = models.ForeignKey(BookInfo,on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)

	
	def price_subtotal(self):
		subtotal = self.book.Price * self.quantity
		return subtotal


	def __str__(self):
		return str(self.cart.currentuser)
	
#class Order(models.Model):
	#order_id = models.CharField()
	#user_cart = models.ForeignKey(Cart,on_delete=)

Carts/forms.py
from django import forms
from .models import CartItem

class CartItemForm(forms.ModelForm):
	class Meta:
		model = CartItem
		fields = ('quantity',)

Carts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from acubook.views import user_login
from .forms import CartItemForm
from acubook.models import BookInfo,UserProfileInfo
from .models import Cart,CartItem
from django.contrib.auth.models import User
from django.core import validators
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings 
from django.http.response import JsonResponse 
from django.views.decorators.csrf import csrf_exempt
import stripe 

# Create your views here.


def cart(request):
	cart_qty = CartItemForm()
	book_title= request.GET.get("title")
	books = BookInfo.objects.get(Title=book_title)
	book_qty = books.Quantity
	username = None

	if request.user.is_authenticated:
		username = request.user
		if request.method == 'POST':
			quantity = request.POST.get('quantity')

			if int(quantity) > book_qty:
				messages.error(request,'The requested quantity for %s is not available' %(book_title)
				) 
			else:
				user_profile = UserProfileInfo.objects.get(user=username)
				Cart.objects.get_or_create(currentuser=user_profile)
				carts = Cart.objects.get(currentuser=user_profile)
				cart_num = carts.id
				cart_obj = Cart.objects.get(id=cart_num)
				try:
					CartItem.objects.filter(cart=cart_obj,book=books).update(quantity=quantity)
					cart_item = CartItem.objects.filter(cart=cart_obj).get(book=books)

				except CartItem.DoesNotExist:
					CartItem.objects.create(cart=cart_obj,book=books,quantity=quantity)

				cart_items = CartItem.objects.filter(cart=cart_obj)
				total_itemNum =  CartItem.objects.filter(cart=cart_obj).count()
				total_cart = 0
				for item in cart_items:
					total_cart += item.price_subtotal()

				if total_cart == 0:
					context = {'cart_item':cart_items,'total_cartitem':total_itemNum,'total_price':total_cart}
					return render(request,'Carts/cart-empty.html',context)
				else:
					context = {'cart_item':cart_items,'total_cartitem':total_itemNum,'total_price':total_cart}
					return render(request,'Carts/cartpage.html',context)
	else:
		return render(request,'acubook/login.html')


def update_cart(request):
	username = None
	book_title = request.GET.get("title")
	books = BookInfo.objects.get(Title=book_title)
	if request.user.is_authenticated:
		username = request.user

		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)
		cart_item = CartItem.objects.filter(cart=carts,book=books)
		cart_item.delete()

		cart_items = CartItem.objects.filter(cart=carts)
		total_itemNum =  CartItem.objects.filter(cart=carts).count()
		total_cart = 0
		for item in cart_items:
			total_cart += item.price_subtotal()
		if total_cart == 0:
			context = {'cart_item':cart_items,'total_cartitem':total_itemNum,'total_price':total_cart}
			return render(request,'Carts/cart-empty.html',context)
		else:
			context = {'cart_item':cart_items,'total_cartitem':total_itemNum,'total_price':total_cart}
			return render(request,'Carts/cartpage.html',context)
	else:
		return render(request,'Carts/cartpage.html',{'cart_qty':cart_qty})


def display_cart(request):
	username = None
	if request.user.is_authenticated:
		username = request.user
		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)

		cart_items = CartItem.objects.filter(cart=carts)

		total_itemNum =  CartItem.objects.filter(cart=carts).count()
		total_cart = 0
		for item in cart_items:
			total_cart += item.price_subtotal()

		if total_cart == 0:
			context = {'cart_item':cart_items,'total_cartitem':total_itemNum,'total_price':total_cart}
			return render(request,'Carts/cart-empty.html',context)
		else:
			context = {'cart_item':cart_items,'total_cartitem':total_itemNum,'total_price':total_cart}
			return render(request,'Carts/cartpage.html',context)
	else:
		return render(request,'acubook/login.html')


def clear_cart(request):
	username = None
	if request.user.is_authenticated:
		username = request.user

		user_profile = UserProfileInfo.objects.get(user=username)
		Cart.objects.get_or_create(currentuser=user_profile)
		carts = Cart.objects.get(currentuser=user_profile)

		cart_items = CartItem.objects.filter(cart=carts)
		cart_items.delete()

		total_itemNum =  0
		total_cart = 0

		context = {'total_cartitem':total_itemNum,'total_price':total_cart}

		return render(request,'Carts/cart-empty.html',context)


def stripe_page(request):
	return render(request,'Carts/stripe_page.html')

@csrf_exempt
def stripe_config(request):
    if request.method == 'GET':
        stripe_config = {'publicKey': settings.STRIPE_PUBLISHABLE_KEY}
        return JsonResponse(stripe_config, safe=False)

@csrf_exempt
def create_checkout_session(request):
    if request.method == 'GET':
        domain_url = 'http://localhost:8000/cart/stripe-page/'
        stripe.api_key = settings.STRIPE_SECRET_KEY
        try:
            # Create new Checkout Session for the order
            # Other optional params include:
            # [billing_address_collection] - to display billing address details on the page
            # [customer] - if you have an existing Stripe Customer ID
            # [payment_intent_data] - lets capture the payment later
            # [customer_email] - lets you prefill the email input in the form
            # For full details see https:#stripe.com/docs/api/checkout/sessions/create

            # ?session_id={CHECKOUT_SESSION_ID} means the redirect will have the session ID set as a query param
            checkout_session = stripe.checkout.Session.create(
                success_url=domain_url + 'success?session_id={CHECKOUT_SESSION_ID}',
                cancel_url=domain_url + 'cancelled/',
                payment_method_types=['card'],
                mode='payment',
                line_items=[
                    {
                        'name': 'T-shirt',
                        'quantity': 1,
                        'currency': 'usd',
                        'amount': '2000',
                    }
                ]
            )
            return JsonResponse({'sessionId': checkout_session['id']})
        except Exception as e:
            return JsonResponse({'error': str(e)})

templates/Carts/cart-empty.html
{% extends "acubook/base.html" %}
{% block body_block %}
{% load static %}
	
	<div class="row text-center">
		<div class="col-lg-12">
			<div class="jumbotron">
			<h1>Shopping Cart is Empty</h1>
			<p>You have no item in your shopping cart. </p>
			<p>Click below to continue Shopping</p>
			<p><a href="{% url 'acubook:index' %}" role="button" class="btn btn-info carts">Continue Shopping</a></p>
		</div>
		</div>
		
	</div>
	

{% endblock %}

templates/Carts/cartpage.html
{% extends "acubook/base.html" %}
{% block body_block %}
{% load static %}

<div class="container">
	<div class="row text-center">
		<div class="col-lg-12">
			<h2 class="cardheader cart">Shopping Cart</h2>
		</div>
		<div class="col-lg-10 table-responsive-lg">
			<table class="table table-hover table-striped">
				<thead class="thead-dark">
					<tr>
						<th scope="col">Book Image</th>
						<th scope="col">Book Title</th>
						<th scope="col">Unit Price</th>
						<th scope="col">Qty</th>
						<th scope="col">Subtotal </th>
					</tr>
				</thead>
				<!-- Create a loop of the cart items -->
				{% for item in cart_item %}
				<tr class="table-row">
					<td> <img src="{{ item.book.Book_image.url }}"></td>
					<td id="book-title">{{ item.book.Title }}</td>
					<td>#{{ item.book.Price }}</td>
					<td>{{ item.quantity }}</td>
					<td>#{{ item.price_subtotal }} &nbsp&nbsp<a href="{% url 'Carts:cart-update' %}?title={{ item.book.Title }}"><i class="fa fa-trash" aria-hidden="true"></i></a></td>

				</tr>
				{% endfor %}
				<!-- End the loop of the cart items -->
				<tr class="table-row">
					<td class="button-td"><a href="{% url 'acubook:index' %}" role="button" class="btn btn-info carts">Continue Shopping</a></td>
					<td class="table-td"></td>
					<td class="table-td"></td>
					<td></td>
					<td class="button-td"><a href="{% url 'Carts:clear-cart' %}" role="button" class="btn btn-secondary carts">Clear Cart</a></td>
				</tr>
			</table>
		</div>
		<br>
		
	</div>
	<br>
	<div class="row">
		<div class="col-lg-3 cart-div">
			<div class="card"> 
            <div class="card-body">
              <h5 class="card-title">Shopping Cart Total</h5>
              <br>
              <p class="card-text total-text">Grand Total:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp#{{ total_price }}</p>
              <a href="{% url 'Carts:stripe-page' %}" role="button" class="btn btn-info carts">Checkout to Payment</a>
			</div>
			</div>
		</div>
		</div>
	</div>
</div>

{% endblock %}

templates/Carts/stripe_page.html
{% extends 'acubook/base.html' %}

{% block body_block %}
      <button class="button is-primary" id="submitBtn">Purchase!</button>
{% endblock %}